name: "Build and push docker images"

on:
  push:
    branches:
      - 'main'

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pg_version: [14, 15, 16]

    name: "Building image with Postgres ${{ matrix.pg_version }}"

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: webidfr/boo:2025-postgres-${{ matrix.pg_version }}
          context: .
          file: Dockerfile
          build-args: |
            PG_VERSION=${{ matrix.pg_version }}
          platforms: linux/amd64,linux/arm64
