name: Tests

on: [push]

jobs:
  tests:
    name: Tests
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: [ '8.1', '8.2' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: .env copy
        run: cp .env.example .env

      # - name: Replacing .env values
      #   run: |
      #     sed -i -e 's/DB_PASSWORD.*/DB_PASSWORD=''/" .env

      - name: Starting MySQL
        run: sudo systemctl start mysql.service

      - name: Setup project
        run: make install

      - name: Phpunit
        run: bin/phpunit

      - name: Phpstan
        run: bin/phpstan

      - name: Correction automatique des coding standards
        run: bin/phpcbf
        continue-on-error: true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '*.php'
          commit_message: ":robot::art: Fix CS"

      - name: Verification des coding standards après correction automatique
        run: bin/phpcs

      # On failure
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: '#boo'
          SLACK_COLOR: '#FF5555'
          SLACK_USERNAME: 'BOO'
          SLACK_ICON_EMOJI: ':ghost:'
          SLACK_TITLE: Dernier commit
          SLACK_FOOTER: "“Boh ça va, ça marche en local non ?” — David Goodenough"
